---

- name: Create aggregate groups
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_nova_host_aggregate:
    state: "{{ resource_state }}"
    cloud: "{{ item.0.cloud_name | default(cloud_name) }}"
    name: "{{ item.0.name }}"
    hosts: "{{ item.0.hosts }}"
    metadata: "{{ item.1 }}"
    availability_zone: "{{ item.0.name | default(aggregate_groups[0].name) }}"
  loop: "{{ aggregate_groups | subelements('metadata', 'skip_missing=True') }}"
