# TODO (vkhitrin): Refactor tasks to fetch MACs in single play
- name: Parse DuT MACs
  set_fact:
    dut_macs: "{{ hostvars[groups[dut_group][0]]['dut_macs'] }}"
  when:
    - hostvars[groups[dut_group][0]]['dut_macs'] is defined
    - dut_macs is not defined

- name: Report unsupported load balance control if requested
  fail: msg="unsupported load balance '{{ pmd_lb }}' is requested"
  when:
    - pmd_lb not in ['ovs', 'user']

- name: Initialize PMD load balance
  block:
    - name: Set time period for load balance pretest profile
      set_fact:
        pmd_lb_pretest_sec: "{{ trex_search }}"
      when:
        - pmd_lb_pretest_sec is not defined

    - name: Start PMD load balance in DuT
      include_tasks: pmd_load_balance/start.yml
  delegate_to: "{{ dut_compute }}"
  become: True
  when:
    - pmd_lb in ['ovs', 'user']

- name: Set Binary Search Command
  set_fact:
    traffic_cmd: >
      {{ binary_search_bin }} --traffic-generator trex-txrx
      --frame-size {{ trex_frame_size }}
      --max-loss-pct {{ trex_max_lost_pct }}
      --send-teaching-warmup
      --dst-macs {{ dut_macs }}
      --num-flows {{ trex_flows }}
      {% if trex_set_vlan %}
        --vlan-ids {{ trex_instance_sriov_vlans|join(',') }}
      {%- endif %}
      --use-src-ip-flows 1
      --use-dst-ip-flows 1
      --use-src-mac-flows 0
      --use-dst-mac-flows 0
      --use-src-port-flows 1
      --use-dst-port-flows 1
      --validation-runtime {{ trex_validation }}
      --search-runtime {{ trex_search }}
      {% if dut_type == 'dpdk' %}
        --rate {{ trex_rate }}
      {%- endif %}
  when: traffic_cmd is not defined

# TODO: Proper print function
- name: Pause PMD load balance
  become: True
  delegate_to: "{{ dut_compute }}"
  block:
    - include_tasks: pmd_load_balance/pause.yml
  when:
    - pmd_lb in ['ovs', 'user']
    - pmd_lb_pretest == True

- name: Run Binary Search Script
  shell: "{{ traffic_cmd }}"
  register: perf_output
  until: perf_output.rc == 0
  retries: 3
  delay: 10
  ignore_errors: yes
  failed_when: False
  become: True

- debug:
    var: perf_output

- name: Stop PMD load balance and report its status
  block:
    - name: Stop PMD load balance in DuT
      include_tasks: pmd_load_balance/stop.yml

    - name: Status of PMD load balance
      include_tasks: pmd-load-balance/status.yml
  delegate_to: "{{ dut_compute }}"
  become: True
  when:
    - pmd_lb in ['ovs', 'user']

- name: Save PMD load balance status into File
  copy:
    content: "{{ pmd_lb_status_output['stdout'] }}"
    dest: "{{ pmd_lb_status_log }}"
  delegate_to: "{{ groups['undercloud'] | first }}"
  when:
    - pmd_lb in ['ovs', 'user']

- name: Save Binary Search Script Result To File
  copy:
    content: "{{ perf_output['stdout'] }}"
    dest: "{{ binary_perf_log }}"
  delegate_to: "{{ groups['undercloud'] | first }}"

- name: Stop TestPMD On DuT
  shell: "tmux list-sessions -F '#S' | xargs -n1 tmux kill-session -t"
  become: True
  delegate_to: "{{ groups[dut_group] | first }}"

- name: Parse JSON Result From Output File
  block:
    - name: Read Performance Result Log
      slurp:
        src: "{{ binary_perf_log }}"
      register: perf_result

    - name: Parse Perfomance Log To JSON Format
      set_fact:
        perf_json: "{{ perf_result['content'] | b64decode | replace('RESULT', '') }}"
  delegate_to: "{{ groups['undercloud'] | first }}"

- name: Fetch OVS version from compute node
  shell: "ovs-vsctl --version | grep 'Open vSwitch' | sed 's/ovs-vsctl \\(.*\\) //'"
  register: compute_ovs_version
  delegate_to: "{{ dut_compute }}"

- name: Fetch puddle/compose from undercloud
  slurp:
    src: /home/stack/core_puddle_version
  register: deployment_core_puddle
  delegate_to: "{{ groups['undercloud'] | first }}"

- name: Append extra info to performance log
  lineinfile:
    path: "{{ binary_perf_log }}"
    line: "{{ item }}"
  loop:
    - "OVS_Version: {{ compute_ovs_version['stdout'] }}"
    - "Puddle: {{ deployment_core_puddle['content'] | b64decode }}"
  delegate_to: "{{ groups['undercloud'] | first }}"

- name: Print Perfomance Result JSON
  debug:
    var: perf_json

# TODO: Add additional valuable information for both states
- name: Print Performance Result
  debug:
    msg: |
      binary-search command:
      {{ perf_output['cmd'] }}

      {% if perf_output.rc == 0 %}

      Performance Flow Succeded

      {% else %}

      Performance Flow Failed

      {% endif %}
  failed_when: perf_output['rc'] != 0
