- name: Status of OVS controlled PMD load balance in DuT
  shell: true
  register: pmd_lb_status_output
  when:
    - pmd_lb == 'ovs'

- name: Status of user controlled PMD load balance in DuT
  shell: podman exec openvswitch_dpdk_netcontrold ncd_ctl status
  register: pmd_lb_status_output
  when:
    - pmd_lb == 'user'

- debug:
    var: pmd_lb_status_output

- name: Save PMD load balance status in DuT
  copy:
    content: "{{ pmd_lb_status_output['stdout'] }}"
    dest: "{{ pmd_lb_status_log }}"
